export const POST_SUCCESS = 'POST_SUCCESS';
export const POST_ERROR = 'POST_ERROR';

export const GET_IMAGE_SUCCESS = 'GET_IMAGE_SUCCESS';
export const GET_IMAGE_ERROR = 'GET_IMAGE_ERROR';

export const ON_LIKE_SUCCESS = 'ON_LIKE_SUCCESS';
export const ON_LIKE_ERROR = 'ON_LIKE_ERROR';

export const FEEDBACK_SUCCESS = 'FEEDBACK_SUCCESS';
export const FEEDBACK_ERROR = 'FEEDBACK_ERROR';